#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

require __DIR__.'/vendor/autoload.php';

$app = require __DIR__.'/bootstrap/app.php';

$input = new Symfony\Component\Console\Input\ArgvInput();
$status = $app->handleCommand($input);

exit($status);